name: Bug report
description:  Report a bug or issue with the app
title: "[Issue]: "
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: A clear & concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: repsteps
    attributes:
      label: Steps to reproduce the issue
      placeholder: |
        1. Go to ...
        2. Tap on ...
        3. See error
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: The device you found this issue on
      options:
        - de-Googled
        - microG
        - Both de-Googled & microG
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error messages/logs
      description: |
        To help diagnose the issue more effectively, please provide any relevant error messages or logs.
        This is mandatory if the app is crashing.
        You can easily capture & share logs using the [LogFox](https://github.com/F0x1d/LogFox) app.
    validations:
      required: false
  - type: textarea
    id: addcontext
    attributes:
      label: Additional context
      description: Any other relevant information or context that can help us understand the issue.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By reporting this issue, you acknowledge the following
      options:
        - label: This issue occurs on the [latest version](https://github.com/techlore/Plexus-app/releases/latest).
          required: true
        - label: This is not a duplicate of another issue.
          required: true
